
@startuml
skinparam style strictuml
title RDCU - annulerSession() avec changement d'état explicite

participant Guichet
participant EtatAttenteNIP
participant EtatAttenteCarte

 -> Guichet : annulerSession()
activate Guichet

Guichet -> EtatAttenteNIP : annulerSession()
activate EtatAttenteNIP

EtatAttenteNIP -> Guichet : ejecterCarte()
EtatAttenteNIP -> Guichet : changerEtat(new EtatAttenteCarte(guichet))

deactivate EtatAttenteNIP

note right of Guichet
Le changement d'état est explicite :
EtatAttenteNIP → EtatAttenteCarte
end note

deactivate Guichet

@enduml